#!/bin/bash
# config.sh — Flashchat Configuration Loader
#
# Loads configuration with the following priority (highest to lowest):
#   1. --config FILE (explicit override)
#   2. ~/.config/flashchat/config (user)
#   3. Environment variables (FLASHCHAT_*)
#   4. Registry/default values
#
# Usage:
#   source lib/config.sh          # Load config
#   flashchat_load_config          # Initialize (creates default if missing)
#   flashchat_get "KEY"           # Get a config value

set -e

FLASHCHAT_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FLASHCHAT_REPO_ROOT="$(cd "${FLASHCHAT_LIB_DIR}/.." && pwd)"
FLASHCHAT_CONFIG_DIR="${HOME}/.config/flashchat"
FLASHCHAT_CONFIG_FILE=""
# Registry: prefer the resolved view generated by modelmgr (includes
# user-added models from models.d/); the shipped assets/model_configs.json
# (itself generated from assets/models/*.json) is the first-run fallback.
if [ -z "${FLASHCHAT_MODEL_CONFIG:-}" ] && [ -f "${FLASHCHAT_CONFIG_DIR}/resolved_models.json" ]; then
    FLASHCHAT_MODEL_CONFIG="${FLASHCHAT_CONFIG_DIR}/resolved_models.json"
fi
FLASHCHAT_MODEL_CONFIG="${FLASHCHAT_MODEL_CONFIG:-${FLASHCHAT_REPO_ROOT}/assets/model_configs.json}"

# Config schema version. Bump when a new persistent key is added so existing user
# configs get the new key backfilled on next load (see _flashchat_migrate_config).
# Because the engine now reads the config file directly, the file must be complete.
FLASHCHAT_CONFIG_SCHEMA_VERSION="7"

# Default configuration values
FLASHCHAT_DEFAULT_MODEL="Qwen-Qwen36-35B-A3B"
FLASHCHAT_DEFAULT_MAX_TOKENS="8192"
FLASHCHAT_DEFAULT_SERVER_PORT="8000"
FLASHCHAT_DEFAULT_SERVER_HOST="127.0.0.1"
FLASHCHAT_DEFAULT_SERVER_LOG_PATH="${FLASHCHAT_CONFIG_DIR}/logs/server.log"
FLASHCHAT_DEFAULT_SHOW_THINKING="0"
FLASHCHAT_DEFAULT_SERVER_DEBUG="0"
FLASHCHAT_DEFAULT_SERVER_HTTP_LOG="0"
FLASHCHAT_DEFAULT_BATCH_PREFILL="0"
FLASHCHAT_DEFAULT_PREFILL_CHUNK="256"
FLASHCHAT_DEFAULT_PREFILL_DEBUG="0"
FLASHCHAT_DEFAULT_ANE_PREFILL="0"
FLASHCHAT_DEFAULT_PREAD_PROFILE=""
FLASHCHAT_DEFAULT_PREAD_PROFILE_CAP="2097152"
FLASHCHAT_DEFAULT_EXPERT_PIN_MAX_GB="4"
FLASHCHAT_DEFAULT_EXPERT_PIN_AUTO_FRAC="0.5"
FLASHCHAT_DEFAULT_EXPERT_PIN_MLOCK="0"
FLASHCHAT_DEFAULT_SYSTEM_PROMPT_CACHE="1"
FLASHCHAT_DEFAULT_SYSTEM_PROMPT_CACHE_MAX_ENTRIES="2"
FLASHCHAT_DEFAULT_SYSTEM_PROMPT_CACHE_DIR=""
FLASHCHAT_DEFAULT_MTP=""
FLASHCHAT_DEFAULT_MTP_BF16="0"
FLASHCHAT_DEFAULT_ACTIVE_EXPERTS=""
FLASHCHAT_DEFAULT_KV_QUANT=""
FLASHCHAT_DEFAULT_CONTEXT_WINDOW=""
FLASHCHAT_MAX_ACTIVE_EXPERTS="16"
FLASHCHAT_DEFAULT_COLOR_OUTPUT="1"
FLASHCHAT_DEFAULT_SAMPLING_PROFILE=""
FLASHCHAT_DEFAULT_REASONING="0"
FLASHCHAT_DEFAULT_TEMPERATURE="0.7"
FLASHCHAT_DEFAULT_TOP_P="0.8"
FLASHCHAT_DEFAULT_TOP_K="20"
FLASHCHAT_DEFAULT_MIN_P="0.0"
FLASHCHAT_DEFAULT_PRESENCE_PENALTY="1.5"
FLASHCHAT_DEFAULT_REPETITION_PENALTY="1.0"
FLASHCHAT_DEFAULT_HUGGINGFACE_CACHE_DIR="${HOME}/.cache/huggingface/hub"
FLASHCHAT_DEFAULT_OFFLOAD_DIR=""

# Config values (set after loading)
CONFIG_SCHEMA_VERSION=""
MODEL=""
MODEL_REPO=""
MAX_TOKENS=""
SERVER_PORT=""
SERVER_HOST=""
SERVER_LOG_PATH=""
SHOW_THINKING=""
SERVER_DEBUG=""
SERVER_HTTP_LOG=""
BATCH_PREFILL=""
PREFILL_CHUNK=""
PREFILL_DEBUG=""
ANE_PREFILL=""
PREAD_PROFILE=""
PREAD_PROFILE_CAP=""
EXPERT_PIN_MAX_GB=""
EXPERT_PIN_AUTO_FRAC=""
EXPERT_PIN_MLOCK=""
SYSTEM_PROMPT_CACHE=""
SYSTEM_PROMPT_CACHE_MAX_ENTRIES=""
SYSTEM_PROMPT_CACHE_DIR=""
MTP=""
MTP_BF16=""
ACTIVE_EXPERTS=""
KV_QUANT=""
CONTEXT_WINDOW=""
COLOR_OUTPUT=""
SAMPLING_PROFILE=""
REASONING=""
TEMPERATURE=""
TOP_P=""
TOP_K=""
MIN_P=""
PRESENCE_PENALTY=""
REPETITION_PENALTY=""
HUGGINGFACE_CACHE_DIR=""
OFFLOAD_DIR=""

# Derived paths (computed after config load)
MODEL_PATH=""
WEIGHTS_DIR=""
EXPERTS_DIR=""

# -----------------------------------------------------------------------------
# Look up model defaults from the bundled model registry.
# -----------------------------------------------------------------------------
flashchat_default_model() {
    local config_file="$FLASHCHAT_MODEL_CONFIG"
    if [ -f "$config_file" ] && command -v python3 >/dev/null 2>&1; then
        python3 -c "
import json, sys
try:
    with open(sys.argv[1]) as f:
        data = json.load(f)
    print(data.get('default_model') or sys.argv[2])
except Exception:
    print(sys.argv[2])
" "$config_file" "$FLASHCHAT_DEFAULT_MODEL" 2>/dev/null
    else
        echo "$FLASHCHAT_DEFAULT_MODEL"
    fi
}

_flashchat_lookup_model_repo() {
    local model_id="${1:-$(flashchat_default_model)}"
    local config_file="$FLASHCHAT_MODEL_CONFIG"
    if [ -f "$config_file" ] && command -v python3 >/dev/null 2>&1; then
        python3 -c "
import json, sys
try:
    with open(sys.argv[1]) as f:
        data = json.load(f)
    model = data.get('models', {}).get(sys.argv[2], {})
    print(model.get('hf_repo', ''))
except Exception:
    pass
" "$config_file" "$model_id" 2>/dev/null
    fi
}

# -----------------------------------------------------------------------------
# Model registry helpers
# -----------------------------------------------------------------------------
flashchat_model_exists() {
    local model_id="$1"
    local config_file="$FLASHCHAT_MODEL_CONFIG"
    [ -n "$model_id" ] || return 1
    [ -f "$config_file" ] || return 1
    python3 -c "
import json, sys
with open(sys.argv[1]) as f:
    data = json.load(f)
sys.exit(0 if sys.argv[2] in data.get('models', {}) else 1)
" "$config_file" "$model_id" 2>/dev/null
}

flashchat_model_field() {
    local model_id="$1"
    local field="$2"
    local config_file="$FLASHCHAT_MODEL_CONFIG"
    [ -n "$model_id" ] || return 1
    [ -n "$field" ] || return 1
    [ -f "$config_file" ] || return 1
    python3 -c "
import json, sys
with open(sys.argv[1]) as f:
    data = json.load(f)
model = data.get('models', {}).get(sys.argv[2], {})
value = model.get(sys.argv[3], '')
print(value if value is not None else '')
" "$config_file" "$model_id" "$field" 2>/dev/null
}

flashchat_model_name() {
    flashchat_model_field "$1" "name"
}

flashchat_model_repo() {
    flashchat_model_field "$1" "hf_repo"
}

flashchat_model_layers() {
    local layers
    layers=$(flashchat_model_field "$1" "num_hidden_layers")
    echo "${layers:-60}"
}

flashchat_model_default_sampling_profile() {
    flashchat_model_field "$1" "default_sampling_profile"
}

flashchat_model_mtp_default() {
    flashchat_model_field "$1" "mtp_default_predictions"
}

flashchat_server_default_field() {
    local field="$1"
    local config_file="$FLASHCHAT_MODEL_CONFIG"
    [ -n "$field" ] || return 1
    [ -f "$config_file" ] || return 1
    python3 -c "
import json, sys
with open(sys.argv[1]) as f:
    data = json.load(f)
value = data.get('server_defaults', {}).get(sys.argv[2], '')
print(value if value is not None else '')
" "$config_file" "$field" 2>/dev/null
}

flashchat_server_mtp_default() {
    flashchat_server_default_field "mtp_default_predictions"
}

flashchat_model_quant_bits() {
    local model_id="$1"
    local config_file="$FLASHCHAT_MODEL_CONFIG"
    [ -n "$model_id" ] || return 1
    [ -f "$config_file" ] || return 1
    python3 -c "
import json, sys
with open(sys.argv[1]) as f:
    data = json.load(f)
model = data.get('models', {}).get(sys.argv[2], {})
quant = model.get('quantization', {})
print(quant.get('bits', 4))
" "$config_file" "$model_id" 2>/dev/null
}

flashchat_model_expert_pack_bytes() {
    local model_id="$1"
    local config_file="$FLASHCHAT_MODEL_CONFIG"
    [ -n "$model_id" ] || return 1
    [ -f "$config_file" ] || return 1
    python3 -c "
import json, sys
with open(sys.argv[1]) as f:
    data = json.load(f)
model = data.get('models', {}).get(sys.argv[2], {})
num_experts = int(model.get('num_experts') or 0)
layers = int(model.get('num_hidden_layers') or 0)
if num_experts <= 0 or layers <= 0:
    print(0)
    sys.exit(0)
hidden = int(model.get('hidden_size') or 0)
moe = int(model.get('moe_intermediate_size') or 0)
quant = model.get('quantization', {})
bits = int(quant.get('bits', 4) or 4)
group_size = int(quant.get('group_size', 64) or 64)
values_per_word = 32 // bits
gate_w = moe * (hidden // values_per_word) * 4
gate_s = moe * (hidden // group_size) * 2
down_w = hidden * (moe // values_per_word) * 4
down_s = hidden * (moe // group_size) * 2
expert_size = gate_w + gate_s + gate_s + gate_w + gate_s + gate_s + down_w + down_s + down_s
print(expert_size * num_experts * layers)
" "$config_file" "$model_id" 2>/dev/null
}

# Resolve the model's trained active-experts (K) from the registry. Returns
# empty string if the field is missing — caller decides what default to use.
flashchat_model_active_experts() {
    flashchat_model_field "$1" "num_experts_per_tok"
}

# Total routed experts for a MoE model (always > 0 for supported models).
flashchat_model_num_experts() {
    local n
    n=$(flashchat_model_field "$1" "num_experts")
    echo "${n:-0}"
}

# Number of system-prompt cache entries (.fcache files) on disk for a model.
# Mirrors the engine's cache-dir resolution: custom dir -> <dir>/<model>/q<bits>/
# system_prompt_cache, else <model_path>/flashchat/q<bits>/system_prompt_cache.
flashchat_sysprompt_cache_count() {
    local model_id="$1" bits custom dir model_path
    [ -n "$model_id" ] || { echo 0; return; }
    bits=$(flashchat_model_quant_bits "$model_id"); bits="${bits:-4}"
    custom=$(flashchat_get SYSTEM_PROMPT_CACHE_DIR)
    if [ -n "$custom" ]; then
        dir="${custom}/${model_id}/q${bits}/system_prompt_cache"
    else
        model_path=$(flashchat_model_path_for_id "$model_id" 2>/dev/null)
        [ -n "$model_path" ] || { echo 0; return; }
        dir="${model_path}/flashchat/q${bits}/system_prompt_cache"
    fi
    find "$dir" -maxdepth 1 -name '*.fcache' 2>/dev/null | wc -l | tr -d ' '
}

# Context-meter inputs for a model: prints "MAX_CONTEXT KV_RAM_BYTES" where
# KV_RAM_BYTES is the wired GPU KV-buffer size for `window` tokens at the given
# kv-quant mode (off|q8|q4). One python call (registry geometry + arithmetic).
flashchat_kv_meter_data() {
    local model_id="$1" window="$2" kvq="$3"
    local config_file="$FLASHCHAT_MODEL_CONFIG"
    [ -n "$model_id" ] && [ -f "$config_file" ] || { echo "0 0"; return 1; }
    python3 -c "
import json, sys
cf, mid, win, kvq = sys.argv[1], sys.argv[2], int(sys.argv[3] or 0), (sys.argv[4] or 'off').lower()
m = json.load(open(cf)).get('models', {}).get(mid, {})
n_kv = int(m.get('num_key_value_heads', 0) or 0)
kv_dim = n_kv * int(m.get('head_dim', 0) or 0)
n_full = int(m.get('num_hidden_layers', 0) or 0) // max(1, int(m.get('full_attention_interval', 1) or 1))
if kvq in ('q8', 'int8', '8'):   per = 2*kv_dim + 2*(n_kv*2)
elif kvq in ('q4', 'int4', '4'): per = 2*(kv_dim//2) + 2*(n_kv*2)
else:                            per = 2*kv_dim*4
print(int(m.get('max_context', 0) or 0), per * n_full * win)
" "$config_file" "$model_id" "$window" "$kvq" 2>/dev/null || echo "0 0"
}

# Resolve the *effective* active-experts value: $FLASHCHAT_ACTIVE_EXPERTS env
# override if set and >0, else the model's trained num_experts_per_tok from
# the registry. The env var is the user's escape hatch (e.g. for sweeping K
# during quality-vs-streaming-cost benchmarks); otherwise the registry is the
# authoritative source for K.
flashchat_effective_active_experts() {
    local override="${ACTIVE_EXPERTS:-${FLASHCHAT_ACTIVE_EXPERTS:-}}"
    if [ -n "$override" ] && [ "$override" -gt 0 ] 2>/dev/null; then
        if [ "$override" -gt "$FLASHCHAT_MAX_ACTIVE_EXPERTS" ] 2>/dev/null; then
            echo "$FLASHCHAT_MAX_ACTIVE_EXPERTS"
            return
        fi
        echo "$override"
        return
    fi
    flashchat_model_active_experts "${MODEL:-$(flashchat_default_model)}"
}

flashchat_model_sampling_profile_field() {
    local model_id="$1"
    local profile_id="$2"
    local field="$3"
    local config_file="$FLASHCHAT_MODEL_CONFIG"
    [ -n "$model_id" ] || return 1
    [ -n "$profile_id" ] || return 1
    [ -n "$field" ] || return 1
    [ -f "$config_file" ] || return 1
    python3 -c "
import json, sys
with open(sys.argv[1]) as f:
    data = json.load(f)
profile = data.get('models', {}).get(sys.argv[2], {}).get('sampling_profiles', {}).get(sys.argv[3], {})
field = sys.argv[4]
value = profile.get(field, '')
if field == 'mtp_default_predictions' and value == '':
    value = profile.get('mtp', '')
print(value if value is not None else '')
" "$config_file" "$model_id" "$profile_id" "$field" 2>/dev/null
}

flashchat_model_sampling_profiles() {
    local model_id="$1"
    local config_file="$FLASHCHAT_MODEL_CONFIG"
    [ -n "$model_id" ] || return 1
    [ -f "$config_file" ] || return 1
    python3 -c "
import json, sys
with open(sys.argv[1]) as f:
    data = json.load(f)
profiles = data.get('models', {}).get(sys.argv[2], {}).get('sampling_profiles', {})
for profile_id, profile in profiles.items():
    print('\\t'.join([
        profile_id,
        str(profile.get('label', profile_id)),
        str(profile.get('description', '')),
        str(profile.get('temperature', '')),
        str(profile.get('top_p', '')),
        str(profile.get('top_k', '')),
        str(profile.get('min_p', '')),
        str(profile.get('presence_penalty', '')),
        str(profile.get('repetition_penalty', '')),
        str(profile.get('reasoning', '')),
        str(profile.get('mtp_default_predictions', profile.get('mtp', ''))),
    ]))
" "$config_file" "$model_id" 2>/dev/null
}

flashchat_model_path_for_id() {
    local repo
    repo=$(flashchat_model_repo "$1")
    [ -n "$repo" ] || return 1
    _flashchat_detect_model_path "$repo"
}

flashchat_model_runtime_dir() {
    local model_id="$1"
    local model_path="$2"
    local bits
    [ -n "$model_path" ] || return 1
    bits=$(flashchat_model_quant_bits "$model_id")
    bits="${bits:-4}"
    echo "${model_path}/flashchat/q${bits}"
}

flashchat_list_models() {
    local config_file="$FLASHCHAT_MODEL_CONFIG"
    [ -f "$config_file" ] || return 1
    python3 -c "
import json, sys
with open(sys.argv[1]) as f:
    data = json.load(f)
for model_id, model in data.get('models', {}).items():
    print('\\t'.join([
        model_id,
        str(model.get('name', model_id)),
        str(model.get('hf_repo', '')),
    ]))
" "$config_file" 2>/dev/null
}

# -----------------------------------------------------------------------------
# Live KV-cache introspection (queries the running infer server's /health)
# -----------------------------------------------------------------------------
# Returns 0 if a fresh /health response is captured, non-zero otherwise. Uses
# a 2s curl timeout so an unreachable server doesn't stall the TUI render —
# the menu is informational, never a control signal.
_flashchat_kv_cache_health_json() {
    local host port url
    # flashchat_server_connect_host is defined in the main launcher script
    # (turns 0.0.0.0/:: into 127.0.0.1 for curl). When lib/config.sh is sourced
    # standalone (other tools, tests) we fall back to 127.0.0.1 to stay
    # self-contained — the menu only ever calls this from the main launcher,
    # so the fallback path is purely defensive.
    if declare -F flashchat_server_connect_host >/dev/null 2>&1; then
        host="$(flashchat_server_connect_host)"
    else
        host="127.0.0.1"
    fi
    port="$(flashchat_get SERVER_PORT)"
    url="http://${host}:${port}/health"
    curl -fsS --max-time 2 "$url" 2>/dev/null
}

# Query /health and pull a single top-level field. Returns empty string if
# the server is down, the field is missing, or the response is unparseable.
# Recognized fields match the infer.m /health payload:
#   context_used       — int: positions filled by the most recent request
#   max_context        — int: configured context window in tokens
#   kv_quantization    — str: "fp32" | "q8" | "q4"
#   kv_total_bytes     — int: bytes of GPU buffer footprint at the configured window
flashchat_kv_cache_field() {
    local field="$1"
    [ -n "$field" ] || return 1
    local body
    body="$(_flashchat_kv_cache_health_json)" || return 1
    [ -n "$body" ] || return 1
    python3 -c "
import json, sys
try:
    data = json.loads(sys.argv[1])
except Exception:
    sys.exit(1)
val = data.get(sys.argv[2], '')
if isinstance(val, bool):
    print('true' if val else 'false')
elif val is None:
    print('')
else:
    print(val)
" "$body" "$field" 2>/dev/null
}

# Convenience: live KV-cache quantization label with a graceful fallback so
# the TUI menu always shows *something* even when /health is unreachable
# (cold start, server stopped, port collision). Falls back to the user-config
# value, then to "fp32" — the same default the infer binary uses when
# FLASHCHAT_KV_QUANT is unset. This keeps the menu label stable across the
# "server not yet running" → "server starting" → "server running" transitions.
flashchat_kv_cache_quantization() {
    local q
    q="$(flashchat_kv_cache_field kv_quantization 2>/dev/null)"
    if [ -n "$q" ]; then
        echo "$q"
        return
    fi
    q=$(flashchat_get KV_QUANT)
    case "$q" in
        q8|8)  echo "q8" ;;
        q4|4)  echo "q4" ;;
        *)     echo "fp32" ;;
    esac
}

# Returns the live "context_used" position count, or 0 when /health is
# unreachable. The meter renders "0k" gracefully on cold start.
flashchat_kv_cache_used() {
    local v
    v="$(flashchat_kv_cache_field context_used 2>/dev/null)"
    [ -n "$v" ] && echo "$v"
    return 0   # empty field is a valid "unavailable", not a failure (set -e safe)
}

# Returns the server's resolved context window in tokens, or the
# config-derived CONTEXT_WINDOW as a fallback. Empty string only when neither
# is available (the meter renders with max=0 → empty bar).
flashchat_kv_cache_max() {
    local v
    v="$(flashchat_kv_cache_field max_context 2>/dev/null)"
    if [ -n "$v" ]; then
        echo "$v"
        return
    fi
    v=$(flashchat_get CONTEXT_WINDOW)
    [ -n "$v" ] && echo "$v"
    return 0   # empty field is a valid "unavailable", not a failure (set -e safe)
}

# Returns the configured-window KV cache footprint in bytes, or 0 when not
# available (meter renders "(0 MiB)" rather than empty parens).
flashchat_kv_cache_total_bytes() {
    local v
    v="$(flashchat_kv_cache_field kv_total_bytes 2>/dev/null)"
    [ -n "$v" ] && echo "$v"
    return 0   # empty field is a valid "unavailable", not a failure (set -e safe)
}

# -----------------------------------------------------------------------------
# Detect the HuggingFace snapshot path from model repo
# -----------------------------------------------------------------------------
_flashchat_detect_model_path() {
    local repo="$1"
    local escaped_repo="${repo//\//--}"
    local hf_cache="${HUGGINGFACE_CACHE_DIR:-$FLASHCHAT_DEFAULT_HUGGINGFACE_CACHE_DIR}"
    
    # Try to find the latest snapshot
    local snapshot_dir="${hf_cache}/models--${escaped_repo}/snapshots"
    
    if [ -d "$snapshot_dir" ]; then
        # Find the latest snapshot (directory with longest name)
        local latest=$(ls -1 "$snapshot_dir" 2>/dev/null | sort | tail -1)
        if [ -n "$latest" ]; then
            echo "${snapshot_dir}/${latest}"
            return 0
        fi
    fi
    
    # Return expected path even if it doesn't exist (for setup prompts)
    echo "${snapshot_dir}/<snapshot>"
}

# -----------------------------------------------------------------------------
# Compute derived paths based on config
# -----------------------------------------------------------------------------
_flashchat_compute_paths() {
    local runtime_dir
    if [ -n "$MODEL_PATH" ]; then
        runtime_dir=$(flashchat_model_runtime_dir "$MODEL" "$MODEL_PATH")
        WEIGHTS_DIR="${WEIGHTS_DIR:-$runtime_dir}"
        EXPERTS_DIR="${EXPERTS_DIR:-${WEIGHTS_DIR}/packed_experts}"
    else
        local detected_path
        detected_path=$(_flashchat_detect_model_path "$MODEL_REPO")
        MODEL_PATH="$detected_path"
        runtime_dir=$(flashchat_model_runtime_dir "$MODEL" "$detected_path")
        WEIGHTS_DIR="${WEIGHTS_DIR:-$runtime_dir}"
        EXPERTS_DIR="${EXPERTS_DIR:-${WEIGHTS_DIR}/packed_experts}"
    fi
}

# -----------------------------------------------------------------------------
# Load configuration from file
# -----------------------------------------------------------------------------
_flashchat_source_config() {
    local config_file="$1"
    if [ -f "$config_file" ]; then
        source "$config_file"
    fi
}

# -----------------------------------------------------------------------------
# Load configuration with priority
# -----------------------------------------------------------------------------
# Backfill any persistent keys missing from an existing config file, then stamp the
# schema version. APPEND-ONLY: existing keys and values are never modified or
# reordered, so this can never corrupt a user's settings — it only adds keys that
# are absent (with the value already resolved by flashchat_load_config). Idempotent:
# once the file carries the current schema version, this returns immediately.
# Must be called AFTER all values are resolved (defaults/profile applied).
_flashchat_migrate_config() {
    local file="$1"
    [ -n "$file" ] && [ -f "$file" ] || return 0
    local file_version
    file_version=$(sed -n 's/^CONFIG_SCHEMA_VERSION="\{0,1\}\([^"]*\)"\{0,1\}.*/\1/p' "$file" 2>/dev/null | head -1)
    [ "$file_version" = "$FLASHCHAT_CONFIG_SCHEMA_VERSION" ] && return 0

    local key added=0
    for key in MODEL HUGGINGFACE_CACHE_DIR OFFLOAD_DIR MAX_TOKENS SAMPLING_PROFILE \
               REASONING TEMPERATURE TOP_P TOP_K MIN_P PRESENCE_PENALTY REPETITION_PENALTY \
               SERVER_PORT SERVER_HOST SERVER_LOG_PATH SERVER_DEBUG SERVER_HTTP_LOG \
               BATCH_PREFILL PREFILL_CHUNK PREFILL_DEBUG ANE_PREFILL \
               PREAD_PROFILE PREAD_PROFILE_CAP \
               EXPERT_PIN_MAX_GB EXPERT_PIN_AUTO_FRAC EXPERT_PIN_MLOCK \
               SYSTEM_PROMPT_CACHE SYSTEM_PROMPT_CACHE_MAX_ENTRIES SYSTEM_PROMPT_CACHE_DIR MTP MTP_BF16 ACTIVE_EXPERTS \
               KV_QUANT CONTEXT_WINDOW SHOW_THINKING COLOR_OUTPUT; do
        if ! grep -qE "^${key}=" "$file" 2>/dev/null; then
            printf '%s="%s"\n' "$key" "${!key}" >> "$file"
            added=$((added + 1))
        fi
    done

    if grep -qE '^CONFIG_SCHEMA_VERSION=' "$file" 2>/dev/null; then
        sed -i '' "s/^CONFIG_SCHEMA_VERSION=.*/CONFIG_SCHEMA_VERSION=\"$FLASHCHAT_CONFIG_SCHEMA_VERSION\"/" "$file" 2>/dev/null || true
    else
        printf 'CONFIG_SCHEMA_VERSION="%s"\n' "$FLASHCHAT_CONFIG_SCHEMA_VERSION" >> "$file"
    fi
    if [ "$added" -gt 0 ]; then
        echo "Config migrated to schema v${FLASHCHAT_CONFIG_SCHEMA_VERSION}: backfilled $added missing key(s) in $file" >&2
    fi
    CONFIG_SCHEMA_VERSION="$FLASHCHAT_CONFIG_SCHEMA_VERSION"
    return 0
}

flashchat_load_config() {
    mkdir -p "$FLASHCHAT_CONFIG_DIR"

    CONFIG_SCHEMA_VERSION=""
    MODEL=""
    MODEL_REPO=""
    MAX_TOKENS=""
    SERVER_PORT=""
    SERVER_HOST=""
    SERVER_LOG_PATH=""
    SHOW_THINKING=""
    SERVER_DEBUG=""
    SERVER_HTTP_LOG=""
    BATCH_PREFILL=""
    PREFILL_CHUNK=""
    PREFILL_DEBUG=""
    ANE_PREFILL=""
    PREAD_PROFILE=""
    PREAD_PROFILE_CAP=""
    EXPERT_PIN_MAX_GB=""
    EXPERT_PIN_AUTO_FRAC=""
    EXPERT_PIN_MLOCK=""
    SYSTEM_PROMPT_CACHE=""
    SYSTEM_PROMPT_CACHE_MAX_ENTRIES=""
    SYSTEM_PROMPT_CACHE_DIR=""
    MTP=""
    MTP_BF16=""
    ACTIVE_EXPERTS=""
    KV_QUANT=""
    CONTEXT_WINDOW=""
    COLOR_OUTPUT=""
    SAMPLING_PROFILE=""
    REASONING=""
    TEMPERATURE=""
    TOP_P=""
    TOP_K=""
    MIN_P=""
    PRESENCE_PENALTY=""
    REPETITION_PENALTY=""
    HUGGINGFACE_CACHE_DIR=""
    OFFLOAD_DIR=""
    MODEL_PATH=""
    WEIGHTS_DIR=""
    EXPERTS_DIR=""

    local override_config="${FLASHCHAT_CONFIG_FILE_OVERRIDE:-${CONFIG_FILE:-}}"

    if [ -n "$override_config" ]; then
        FLASHCHAT_CONFIG_FILE="$override_config"
        _flashchat_source_config "$override_config"
    elif [ -f "${FLASHCHAT_CONFIG_DIR}/config" ]; then
        FLASHCHAT_CONFIG_FILE="${FLASHCHAT_CONFIG_DIR}/config"
        _flashchat_source_config "${FLASHCHAT_CONFIG_DIR}/config"
    else
        FLASHCHAT_CONFIG_FILE="${FLASHCHAT_CONFIG_DIR}/config"
    fi
    
    # 3. Environment variables override
    [ -n "$FLASHCHAT_MODEL" ] && MODEL="$FLASHCHAT_MODEL"
    [ -n "$FLASHCHAT_MODEL_PATH" ] && MODEL_PATH="$FLASHCHAT_MODEL_PATH"
    [ -n "$FLASHCHAT_MAX_TOKENS" ] && MAX_TOKENS="$FLASHCHAT_MAX_TOKENS"
    [ -n "$FLASHCHAT_SERVER_PORT" ] && SERVER_PORT="$FLASHCHAT_SERVER_PORT"
    [ -n "$FLASHCHAT_SERVER_HOST" ] && SERVER_HOST="$FLASHCHAT_SERVER_HOST"
    [ -n "$FLASHCHAT_SERVER_LOG" ] && SERVER_LOG_PATH="$FLASHCHAT_SERVER_LOG"
    [ -n "$FLASHCHAT_SHOW_THINKING" ] && SHOW_THINKING="$FLASHCHAT_SHOW_THINKING"
    [ -n "$FLASHCHAT_SERVER_DEBUG" ] && SERVER_DEBUG="$FLASHCHAT_SERVER_DEBUG"
    [ -n "$FLASHCHAT_SERVER_HTTP_LOG" ] && SERVER_HTTP_LOG="$FLASHCHAT_SERVER_HTTP_LOG"
    [ -n "$FLASHCHAT_BATCH_PREFILL" ] && BATCH_PREFILL="$FLASHCHAT_BATCH_PREFILL"
    [ -n "$FLASHCHAT_PREFILL_CHUNK" ] && PREFILL_CHUNK="$FLASHCHAT_PREFILL_CHUNK"
    [ -n "$FLASHCHAT_PREFILL_DEBUG" ] && PREFILL_DEBUG="$FLASHCHAT_PREFILL_DEBUG"
    [ -n "$FLASHCHAT_ANE_PREFILL" ] && ANE_PREFILL="$FLASHCHAT_ANE_PREFILL"
    [ -n "$FLASHCHAT_PREAD_PROFILE" ] && PREAD_PROFILE="$FLASHCHAT_PREAD_PROFILE"
    [ -n "$FLASHCHAT_PREAD_PROFILE_CAP" ] && PREAD_PROFILE_CAP="$FLASHCHAT_PREAD_PROFILE_CAP"
    [ -n "$FLASHCHAT_EXPERT_PIN_MAX_GB" ] && EXPERT_PIN_MAX_GB="$FLASHCHAT_EXPERT_PIN_MAX_GB"
    [ -n "$FLASHCHAT_EXPERT_PIN_AUTO_FRAC" ] && EXPERT_PIN_AUTO_FRAC="$FLASHCHAT_EXPERT_PIN_AUTO_FRAC"
    [ -n "$FLASHCHAT_EXPERT_PIN_MLOCK" ] && EXPERT_PIN_MLOCK="$FLASHCHAT_EXPERT_PIN_MLOCK"
    [ -n "$FLASHCHAT_SYSTEM_PROMPT_CACHE" ] && SYSTEM_PROMPT_CACHE="$FLASHCHAT_SYSTEM_PROMPT_CACHE"
    [ -n "$FLASHCHAT_SYSTEM_PROMPT_CACHE_MAX_ENTRIES" ] && SYSTEM_PROMPT_CACHE_MAX_ENTRIES="$FLASHCHAT_SYSTEM_PROMPT_CACHE_MAX_ENTRIES"
    [ -n "$FLASHCHAT_SYSTEM_PROMPT_CACHE_DIR" ] && SYSTEM_PROMPT_CACHE_DIR="$FLASHCHAT_SYSTEM_PROMPT_CACHE_DIR"
    [ -n "$FLASHCHAT_MTP" ] && MTP="$FLASHCHAT_MTP"
    [ -n "$FLASHCHAT_MTP_BF16" ] && MTP_BF16="$FLASHCHAT_MTP_BF16"
    [ -n "$FLASHCHAT_ACTIVE_EXPERTS" ] && ACTIVE_EXPERTS="$FLASHCHAT_ACTIVE_EXPERTS"
    [ -n "$FLASHCHAT_KV_QUANT" ] && KV_QUANT="$FLASHCHAT_KV_QUANT"
    [ -n "$FLASHCHAT_CONTEXT_WINDOW" ] && CONTEXT_WINDOW="$FLASHCHAT_CONTEXT_WINDOW"
    [ -n "$FLASHCHAT_COLOR_OUTPUT" ] && COLOR_OUTPUT="$FLASHCHAT_COLOR_OUTPUT"
    [ -n "$FLASHCHAT_SAMPLING_PROFILE" ] && SAMPLING_PROFILE="$FLASHCHAT_SAMPLING_PROFILE"
    [ -n "$FLASHCHAT_HUGGINGFACE_CACHE_DIR" ] && HUGGINGFACE_CACHE_DIR="$FLASHCHAT_HUGGINGFACE_CACHE_DIR"
    [ -n "$FLASHCHAT_OFFLOAD_DIR" ] && OFFLOAD_DIR="$FLASHCHAT_OFFLOAD_DIR"
    [ -n "$FLASHCHAT_WEIGHTS_DIR" ] && WEIGHTS_DIR="$FLASHCHAT_WEIGHTS_DIR"
    [ -n "$FLASHCHAT_EXPERTS_DIR" ] && EXPERTS_DIR="$FLASHCHAT_EXPERTS_DIR"
    
    local default_model
    default_model=$(flashchat_default_model)
    if [ -z "$MODEL" ]; then
        MODEL="$default_model"
    fi
    if ! flashchat_model_exists "$MODEL"; then
        if [ -n "$MODEL_REPO" ]; then
            local derived_id="${MODEL_REPO//\//-}"
            derived_id="${derived_id//./}"
            if flashchat_model_exists "$derived_id"; then
                MODEL="$derived_id"
                if [ -f "$FLASHCHAT_CONFIG_FILE" ]; then
                    sed -i '' "s/^MODEL=.*/MODEL=\"$derived_id\"/" "$FLASHCHAT_CONFIG_FILE" 2>/dev/null || true
                fi
            else
                echo "WARNING: model '$MODEL' is not in $FLASHCHAT_MODEL_CONFIG." >&2
                echo "  Run 'flashchat config' to select your model, or set FLASHCHAT_MODEL_REPO." >&2
                echo "  Using default model '$default_model' for now." >&2
                MODEL="$default_model"
            fi
        else
            echo "WARNING: model '$MODEL' is not in $FLASHCHAT_MODEL_CONFIG (may be an old-format ID)." >&2
            echo "  Run 'flashchat config' to select your model again." >&2
            echo "  Using default model '$default_model' for now." >&2
            MODEL="$default_model"
        fi
    fi
    local looked_up_repo
    looked_up_repo=$(_flashchat_lookup_model_repo "$MODEL")
    if [ -n "$looked_up_repo" ]; then
        MODEL_REPO="$looked_up_repo"
    fi
    local default_profile
    default_profile=$(flashchat_model_default_sampling_profile "$MODEL")
    SAMPLING_PROFILE="${SAMPLING_PROFILE:-${default_profile:-$FLASHCHAT_DEFAULT_SAMPLING_PROFILE}}"
    if [ -n "$SAMPLING_PROFILE" ] && [ "$SAMPLING_PROFILE" != "custom" ]; then
        local profile_temperature profile_top_p profile_top_k profile_min_p profile_presence_penalty profile_repetition_penalty profile_reasoning profile_mtp
        profile_temperature=$(flashchat_model_sampling_profile_field "$MODEL" "$SAMPLING_PROFILE" "temperature")
        profile_top_p=$(flashchat_model_sampling_profile_field "$MODEL" "$SAMPLING_PROFILE" "top_p")
        profile_top_k=$(flashchat_model_sampling_profile_field "$MODEL" "$SAMPLING_PROFILE" "top_k")
        profile_min_p=$(flashchat_model_sampling_profile_field "$MODEL" "$SAMPLING_PROFILE" "min_p")
        profile_presence_penalty=$(flashchat_model_sampling_profile_field "$MODEL" "$SAMPLING_PROFILE" "presence_penalty")
        profile_repetition_penalty=$(flashchat_model_sampling_profile_field "$MODEL" "$SAMPLING_PROFILE" "repetition_penalty")
        profile_reasoning=$(flashchat_model_sampling_profile_field "$MODEL" "$SAMPLING_PROFILE" "reasoning")
        profile_mtp=$(flashchat_model_sampling_profile_field "$MODEL" "$SAMPLING_PROFILE" "mtp_default_predictions")
        if [ -z "$profile_mtp" ]; then
            profile_mtp=$(flashchat_model_sampling_profile_field "$MODEL" "$SAMPLING_PROFILE" "mtp")
        fi
        [ -n "$profile_temperature" ] && TEMPERATURE="$profile_temperature"
        [ -n "$profile_top_p" ] && TOP_P="$profile_top_p"
        [ -n "$profile_top_k" ] && TOP_K="$profile_top_k"
        [ -n "$profile_min_p" ] && MIN_P="$profile_min_p"
        [ -n "$profile_presence_penalty" ] && PRESENCE_PENALTY="$profile_presence_penalty"
        [ -n "$profile_repetition_penalty" ] && REPETITION_PENALTY="$profile_repetition_penalty"
        [ -n "$profile_reasoning" ] && REASONING="$profile_reasoning"
        [ -z "$MTP" ] && [ -n "$profile_mtp" ] && MTP="$profile_mtp"
    fi
    if [ -z "$MTP" ]; then
        local server_mtp_default
        server_mtp_default=$(flashchat_server_mtp_default)
        [ -n "$server_mtp_default" ] && MTP="$server_mtp_default"
    fi
    if [ -z "$MTP" ]; then
        local model_mtp_default
        model_mtp_default=$(flashchat_model_mtp_default "$MODEL")
        [ -n "$model_mtp_default" ] && MTP="$model_mtp_default"
    fi
    MAX_TOKENS="${MAX_TOKENS:-$FLASHCHAT_DEFAULT_MAX_TOKENS}"
    SERVER_PORT="${SERVER_PORT:-$FLASHCHAT_DEFAULT_SERVER_PORT}"
    SERVER_HOST="${SERVER_HOST:-$FLASHCHAT_DEFAULT_SERVER_HOST}"
    SERVER_LOG_PATH="${SERVER_LOG_PATH:-$FLASHCHAT_DEFAULT_SERVER_LOG_PATH}"
    SHOW_THINKING="${SHOW_THINKING:-$FLASHCHAT_DEFAULT_SHOW_THINKING}"
    SERVER_DEBUG="${SERVER_DEBUG:-$FLASHCHAT_DEFAULT_SERVER_DEBUG}"
    SERVER_HTTP_LOG="${SERVER_HTTP_LOG:-$FLASHCHAT_DEFAULT_SERVER_HTTP_LOG}"
    BATCH_PREFILL="${BATCH_PREFILL:-$FLASHCHAT_DEFAULT_BATCH_PREFILL}"
    PREFILL_CHUNK="${PREFILL_CHUNK:-$FLASHCHAT_DEFAULT_PREFILL_CHUNK}"
    PREFILL_DEBUG="${PREFILL_DEBUG:-$FLASHCHAT_DEFAULT_PREFILL_DEBUG}"
    ANE_PREFILL="${ANE_PREFILL:-$FLASHCHAT_DEFAULT_ANE_PREFILL}"
    PREAD_PROFILE="${PREAD_PROFILE:-$FLASHCHAT_DEFAULT_PREAD_PROFILE}"
    PREAD_PROFILE_CAP="${PREAD_PROFILE_CAP:-$FLASHCHAT_DEFAULT_PREAD_PROFILE_CAP}"
    EXPERT_PIN_MAX_GB="${EXPERT_PIN_MAX_GB:-$FLASHCHAT_DEFAULT_EXPERT_PIN_MAX_GB}"
    EXPERT_PIN_AUTO_FRAC="${EXPERT_PIN_AUTO_FRAC:-$FLASHCHAT_DEFAULT_EXPERT_PIN_AUTO_FRAC}"
    EXPERT_PIN_MLOCK="${EXPERT_PIN_MLOCK:-$FLASHCHAT_DEFAULT_EXPERT_PIN_MLOCK}"
    SYSTEM_PROMPT_CACHE="${SYSTEM_PROMPT_CACHE:-$FLASHCHAT_DEFAULT_SYSTEM_PROMPT_CACHE}"
    SYSTEM_PROMPT_CACHE_MAX_ENTRIES="${SYSTEM_PROMPT_CACHE_MAX_ENTRIES:-$FLASHCHAT_DEFAULT_SYSTEM_PROMPT_CACHE_MAX_ENTRIES}"
    SYSTEM_PROMPT_CACHE_DIR="${SYSTEM_PROMPT_CACHE_DIR:-$FLASHCHAT_DEFAULT_SYSTEM_PROMPT_CACHE_DIR}"
    MTP="${MTP:-$FLASHCHAT_DEFAULT_MTP}"
    MTP_BF16="${MTP_BF16:-$FLASHCHAT_DEFAULT_MTP_BF16}"
    ACTIVE_EXPERTS="${ACTIVE_EXPERTS:-$FLASHCHAT_DEFAULT_ACTIVE_EXPERTS}"
    KV_QUANT="${KV_QUANT:-$FLASHCHAT_DEFAULT_KV_QUANT}"
    CONTEXT_WINDOW="${CONTEXT_WINDOW:-$FLASHCHAT_DEFAULT_CONTEXT_WINDOW}"
    COLOR_OUTPUT="${COLOR_OUTPUT:-$FLASHCHAT_DEFAULT_COLOR_OUTPUT}"
    REASONING="${REASONING:-$FLASHCHAT_DEFAULT_REASONING}"
    TEMPERATURE="${TEMPERATURE:-$FLASHCHAT_DEFAULT_TEMPERATURE}"
    TOP_P="${TOP_P:-$FLASHCHAT_DEFAULT_TOP_P}"
    TOP_K="${TOP_K:-$FLASHCHAT_DEFAULT_TOP_K}"
    MIN_P="${MIN_P:-$FLASHCHAT_DEFAULT_MIN_P}"
    PRESENCE_PENALTY="${PRESENCE_PENALTY:-$FLASHCHAT_DEFAULT_PRESENCE_PENALTY}"
    REPETITION_PENALTY="${REPETITION_PENALTY:-$FLASHCHAT_DEFAULT_REPETITION_PENALTY}"
    HUGGINGFACE_CACHE_DIR="${HUGGINGFACE_CACHE_DIR:-$FLASHCHAT_DEFAULT_HUGGINGFACE_CACHE_DIR}"
    OFFLOAD_DIR="${OFFLOAD_DIR:-$FLASHCHAT_DEFAULT_OFFLOAD_DIR}"

    [ -n "$FLASHCHAT_REASONING" ] && REASONING="$FLASHCHAT_REASONING"
    [ -n "$FLASHCHAT_TEMPERATURE" ] && TEMPERATURE="$FLASHCHAT_TEMPERATURE"
    [ -n "$FLASHCHAT_TOP_P" ] && TOP_P="$FLASHCHAT_TOP_P"
    [ -n "$FLASHCHAT_TOP_K" ] && TOP_K="$FLASHCHAT_TOP_K"
    [ -n "$FLASHCHAT_MIN_P" ] && MIN_P="$FLASHCHAT_MIN_P"
    [ -n "$FLASHCHAT_PRESENCE_PENALTY" ] && PRESENCE_PENALTY="$FLASHCHAT_PRESENCE_PENALTY"
    [ -n "$FLASHCHAT_REPETITION_PENALTY" ] && REPETITION_PENALTY="$FLASHCHAT_REPETITION_PENALTY"
    
    # Compute derived paths
    _flashchat_compute_paths

    # Ensure the on-disk config is complete for the current schema (append-only),
    # so the engine — which reads the file directly — sees every key. Never fails
    # the load.
    _flashchat_migrate_config "$FLASHCHAT_CONFIG_FILE" || true
}

# -----------------------------------------------------------------------------
# Get a config value
# -----------------------------------------------------------------------------
flashchat_get() {
    local key="$1"
    case "$key" in
        CONFIG_SCHEMA_VERSION) echo "$CONFIG_SCHEMA_VERSION" ;;
        MODEL) echo "$MODEL" ;;
        MODEL_REPO) echo "$MODEL_REPO" ;;
        MAX_TOKENS) echo "$MAX_TOKENS" ;;
        SERVER_PORT) echo "$SERVER_PORT" ;;
        SERVER_HOST) echo "$SERVER_HOST" ;;
        SERVER_LOG_PATH) echo "$SERVER_LOG_PATH" ;;
        SHOW_THINKING) echo "$SHOW_THINKING" ;;
        SERVER_DEBUG) echo "$SERVER_DEBUG" ;;
        SERVER_HTTP_LOG) echo "$SERVER_HTTP_LOG" ;;
        BATCH_PREFILL) echo "$BATCH_PREFILL" ;;
        PREFILL_CHUNK) echo "$PREFILL_CHUNK" ;;
        PREFILL_DEBUG) echo "$PREFILL_DEBUG" ;;
        ANE_PREFILL) echo "$ANE_PREFILL" ;;
        PREAD_PROFILE) echo "$PREAD_PROFILE" ;;
        PREAD_PROFILE_CAP) echo "$PREAD_PROFILE_CAP" ;;
        EXPERT_PIN_MAX_GB) echo "$EXPERT_PIN_MAX_GB" ;;
        EXPERT_PIN_AUTO_FRAC) echo "$EXPERT_PIN_AUTO_FRAC" ;;
        EXPERT_PIN_MLOCK) echo "$EXPERT_PIN_MLOCK" ;;
        SYSTEM_PROMPT_CACHE) echo "$SYSTEM_PROMPT_CACHE" ;;
        SYSTEM_PROMPT_CACHE_MAX_ENTRIES) echo "$SYSTEM_PROMPT_CACHE_MAX_ENTRIES" ;;
        SYSTEM_PROMPT_CACHE_DIR) echo "$SYSTEM_PROMPT_CACHE_DIR" ;;
        MTP) echo "$MTP" ;;
        MTP_BF16) echo "$MTP_BF16" ;;
        ACTIVE_EXPERTS) echo "$ACTIVE_EXPERTS" ;;
        KV_QUANT) echo "$KV_QUANT" ;;
        CONTEXT_WINDOW) echo "$CONTEXT_WINDOW" ;;
        COLOR_OUTPUT) echo "$COLOR_OUTPUT" ;;
        SAMPLING_PROFILE) echo "$SAMPLING_PROFILE" ;;
        REASONING) echo "$REASONING" ;;
        TEMPERATURE) echo "$TEMPERATURE" ;;
        TOP_P) echo "$TOP_P" ;;
        TOP_K) echo "$TOP_K" ;;
        MIN_P) echo "$MIN_P" ;;
        PRESENCE_PENALTY) echo "$PRESENCE_PENALTY" ;;
        REPETITION_PENALTY) echo "$REPETITION_PENALTY" ;;
        HUGGINGFACE_CACHE_DIR) echo "$HUGGINGFACE_CACHE_DIR" ;;
        OFFLOAD_DIR) echo "$OFFLOAD_DIR" ;;
        MODEL_PATH) echo "$MODEL_PATH" ;;
        WEIGHTS_DIR) echo "$WEIGHTS_DIR" ;;
        EXPERTS_DIR) echo "$EXPERTS_DIR" ;;
        CONFIG_FILE) echo "$FLASHCHAT_CONFIG_FILE" ;;
        CONFIG_DIR) echo "$FLASHCHAT_CONFIG_DIR" ;;
        MODEL_CONFIG) echo "$FLASHCHAT_MODEL_CONFIG" ;;
        *) echo "" ;;
    esac
}

# -----------------------------------------------------------------------------
# Create default config file
# -----------------------------------------------------------------------------
flashchat_create_default_config() {
    local config_file="${FLASHCHAT_CONFIG_FILE:-${FLASHCHAT_CONFIG_DIR}/config}"
    mkdir -p "$(dirname "$config_file")"
    cat > "$config_file" << EOF
# Flashchat Configuration
# Generated on $(date)
CONFIG_SCHEMA_VERSION="${FLASHCHAT_CONFIG_SCHEMA_VERSION}"

# Model Settings
MODEL="${MODEL:-$(flashchat_default_model)}"

# Storage Settings
HUGGINGFACE_CACHE_DIR="${HUGGINGFACE_CACHE_DIR:-$FLASHCHAT_DEFAULT_HUGGINGFACE_CACHE_DIR}"
OFFLOAD_DIR="${OFFLOAD_DIR:-$FLASHCHAT_DEFAULT_OFFLOAD_DIR}"

# Generation Defaults
MAX_TOKENS="${MAX_TOKENS:-$FLASHCHAT_DEFAULT_MAX_TOKENS}"
SAMPLING_PROFILE="${SAMPLING_PROFILE:-${FLASHCHAT_DEFAULT_SAMPLING_PROFILE:-$(flashchat_model_default_sampling_profile "${MODEL:-$(flashchat_default_model)}")}}"
REASONING="${REASONING:-$FLASHCHAT_DEFAULT_REASONING}"
TEMPERATURE="${TEMPERATURE:-$FLASHCHAT_DEFAULT_TEMPERATURE}"
TOP_P="${TOP_P:-$FLASHCHAT_DEFAULT_TOP_P}"
TOP_K="${TOP_K:-$FLASHCHAT_DEFAULT_TOP_K}"
MIN_P="${MIN_P:-$FLASHCHAT_DEFAULT_MIN_P}"
PRESENCE_PENALTY="${PRESENCE_PENALTY:-$FLASHCHAT_DEFAULT_PRESENCE_PENALTY}"
REPETITION_PENALTY="${REPETITION_PENALTY:-$FLASHCHAT_DEFAULT_REPETITION_PENALTY}"

# Server Settings
SERVER_PORT="${SERVER_PORT:-$FLASHCHAT_DEFAULT_SERVER_PORT}"
SERVER_HOST="${SERVER_HOST:-$FLASHCHAT_DEFAULT_SERVER_HOST}"
SERVER_LOG_PATH="${SERVER_LOG_PATH:-$FLASHCHAT_DEFAULT_SERVER_LOG_PATH}"
SERVER_DEBUG="${SERVER_DEBUG:-$FLASHCHAT_DEFAULT_SERVER_DEBUG}"
SERVER_HTTP_LOG="${SERVER_HTTP_LOG:-$FLASHCHAT_DEFAULT_SERVER_HTTP_LOG}"
BATCH_PREFILL="${BATCH_PREFILL:-$FLASHCHAT_DEFAULT_BATCH_PREFILL}"
PREFILL_CHUNK="${PREFILL_CHUNK:-$FLASHCHAT_DEFAULT_PREFILL_CHUNK}"
PREFILL_DEBUG="${PREFILL_DEBUG:-$FLASHCHAT_DEFAULT_PREFILL_DEBUG}"
ANE_PREFILL="${ANE_PREFILL:-$FLASHCHAT_DEFAULT_ANE_PREFILL}"
# Debug: expert-streaming pread timing profile (empty = off; path = write TSV)
PREAD_PROFILE="${PREAD_PROFILE:-$FLASHCHAT_DEFAULT_PREAD_PROFILE}"
PREAD_PROFILE_CAP="${PREAD_PROFILE_CAP:-$FLASHCHAT_DEFAULT_PREAD_PROFILE_CAP}"
# Expert pin-cache: keep hottest experts RAM-resident on low-RAM machines
EXPERT_PIN_MAX_GB="${EXPERT_PIN_MAX_GB:-$FLASHCHAT_DEFAULT_EXPERT_PIN_MAX_GB}"
EXPERT_PIN_AUTO_FRAC="${EXPERT_PIN_AUTO_FRAC:-$FLASHCHAT_DEFAULT_EXPERT_PIN_AUTO_FRAC}"
EXPERT_PIN_MLOCK="${EXPERT_PIN_MLOCK:-$FLASHCHAT_DEFAULT_EXPERT_PIN_MLOCK}"
SYSTEM_PROMPT_CACHE="${SYSTEM_PROMPT_CACHE:-$FLASHCHAT_DEFAULT_SYSTEM_PROMPT_CACHE}"
SYSTEM_PROMPT_CACHE_MAX_ENTRIES="${SYSTEM_PROMPT_CACHE_MAX_ENTRIES:-$FLASHCHAT_DEFAULT_SYSTEM_PROMPT_CACHE_MAX_ENTRIES}"
SYSTEM_PROMPT_CACHE_DIR="${SYSTEM_PROMPT_CACHE_DIR:-$FLASHCHAT_DEFAULT_SYSTEM_PROMPT_CACHE_DIR}"
MTP="${MTP:-$FLASHCHAT_DEFAULT_MTP}"
MTP_BF16="${MTP_BF16:-$FLASHCHAT_DEFAULT_MTP_BF16}"
ACTIVE_EXPERTS="${ACTIVE_EXPERTS:-$FLASHCHAT_DEFAULT_ACTIVE_EXPERTS}"
KV_QUANT="${KV_QUANT:-$FLASHCHAT_DEFAULT_KV_QUANT}"
CONTEXT_WINDOW="${CONTEXT_WINDOW:-$FLASHCHAT_DEFAULT_CONTEXT_WINDOW}"

# UI Settings
SHOW_THINKING="${SHOW_THINKING:-$FLASHCHAT_DEFAULT_SHOW_THINKING}"
COLOR_OUTPUT="${COLOR_OUTPUT:-$FLASHCHAT_DEFAULT_COLOR_OUTPUT}"
EOF
    FLASHCHAT_CONFIG_FILE="$config_file"
}

# -----------------------------------------------------------------------------
# Check if config exists
# -----------------------------------------------------------------------------
flashchat_has_config() {
    local override_config="${FLASHCHAT_CONFIG_FILE_OVERRIDE:-${CONFIG_FILE:-}}"
    if [ -n "$override_config" ]; then
        [ -f "$override_config" ]
    else
        [ -f "${FLASHCHAT_CONFIG_DIR}/config" ]
    fi
}

# -----------------------------------------------------------------------------
# Get PID file path
# -----------------------------------------------------------------------------
flashchat_get_pid_file() {
    echo "${FLASHCHAT_CONFIG_DIR}/server.pid"
}

flashchat_get_server_signature_file() {
    echo "${FLASHCHAT_CONFIG_DIR}/server.signature"
}

# -----------------------------------------------------------------------------
# Get Flashchat user/app state paths
# -----------------------------------------------------------------------------
flashchat_get_data_dir() {
    echo "$FLASHCHAT_CONFIG_DIR"
}

flashchat_get_sessions_dir() {
    echo "${FLASHCHAT_CONFIG_DIR}/sessions"
}

flashchat_get_history_file() {
    echo "${FLASHCHAT_CONFIG_DIR}/history"
}

flashchat_get_system_prompt_file() {
    echo "${FLASHCHAT_CONFIG_DIR}/system.md"
}

# Export functions for use in subshells
export -f flashchat_load_config
export -f flashchat_get
export -f flashchat_create_default_config
export -f flashchat_has_config
export -f flashchat_get_data_dir
export -f flashchat_get_pid_file
export -f flashchat_get_server_signature_file
export -f flashchat_get_sessions_dir
export -f flashchat_get_history_file
export -f flashchat_get_system_prompt_file
export -f flashchat_default_model
export -f flashchat_model_exists
export -f flashchat_model_field
export -f flashchat_model_name
export -f flashchat_model_repo
export -f flashchat_model_layers
export -f flashchat_model_default_sampling_profile
export -f flashchat_model_mtp_default
export -f flashchat_server_default_field
export -f flashchat_server_mtp_default
export -f flashchat_model_quant_bits
export -f flashchat_model_expert_pack_bytes
export -f flashchat_model_sampling_profile_field
export -f flashchat_model_sampling_profiles
export -f flashchat_model_path_for_id
export -f flashchat_list_models
export -f _flashchat_kv_cache_health_json
export -f flashchat_kv_cache_field
export -f flashchat_kv_cache_quantization
export -f flashchat_kv_cache_used
export -f flashchat_kv_cache_max
export -f flashchat_kv_cache_total_bytes
export -f flashchat_kv_meter_data
export -f flashchat_sysprompt_cache_count
